## I didn't put in the MacOS stuff from the amex computer because I was too lazy. but if there's issues with copy and pasting that's why
unbind-key C-b
set -g prefix C-f
bind-key C-f send-prefix

set -g default-terminal $TERM
set -g renumber-windows on
set -g mode-keys vi
set-option -g default-terminal "screen-256color"
set-option -g history-limit 1000

unbind-key '"'
unbind-key %
bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"

bind-key h select-pane -L
bind-key C-h select-pane -L
bind-key j select-pane -D
bind-key C-j select-pane -D
bind-key k select-pane -U
bind-key C-k select-pane -U
bind-key l select-pane -R
bind-key C-l select-pane -R

bind-key H resize-pane -L 5
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key L resize-pane -R 5

set -g base-index 1
setw -g pane-base-index 1

setw -g mouse on

set -g mouse on

unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
